apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-java-app
  labels:
    app: simple-java-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-java-app
  template:
    metadata:
      labels:
        app: simple-java-app
    spec:
      containers:
        - name: simple-java-app
          image: 383946777397.dkr.ecr.ap-south-1.amazonaws.com/simple-java-maven-app:5
          ports:
            - containerPort: 8080
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: simple-java-app-service
spec:
  type: LoadBalancer
  selector:
    app: simple-java-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
